server:
  port: 8783

#设置负载均衡策略
PRODUCT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#设置延时等待时长
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        
        
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  redis:
    database: 0
    host: 172.19.2.222
    port: 6379
    timeout: 2000
  rabbitmq:
    host: 172.19.2.222
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
    virtual-host: /


    


env: test1
branch: master
