server:
  port: 8784

#设置负载均衡策略
PRODUCT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#设置延时等待时长
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 8000
        
        
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  redis:
      database: 0
      host: 47.101.38.34
      port: 6379
      timeout: 2000
  rabbitmq:
      host: 192.168.136.138
      port: 5672
      username: root
      password: a214078
      connection-timeout: 5000
      virtual-host: /

    


env: test
branch: master
